
//! Autogenerated weights for `pallet_project_tips`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-09-23, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `amiya`, CPU: `12th Gen Intel(R) Core(TM) i7-12650H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// target/release/node-template
// benchmark
// pallet
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet-project-tips
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// custom-pallets/project-tips/src/weights.rs
// --template=./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_project_tips`.
pub trait WeightInfo {
	fn create_project() -> Weight;
}

/// Weights for `pallet_project_tips` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ProjectTips::NextProjectId` (r:1 w:1)
	/// Proof: `ProjectTips::NextProjectId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ProjectTips::AccountProjects` (r:1 w:1)
	/// Proof: `ProjectTips::AccountProjects` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ProjectTips::Projects` (r:0 w:1)
	/// Proof: `ProjectTips::Projects` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_project() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `10`
		//  Estimated: `3475`
		// Minimum execution time: 13_363_000 picoseconds.
		Weight::from_parts(14_074_000, 3475)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `ProjectTips::NextProjectId` (r:1 w:1)
	/// Proof: `ProjectTips::NextProjectId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ProjectTips::AccountProjects` (r:1 w:1)
	/// Proof: `ProjectTips::AccountProjects` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ProjectTips::Projects` (r:0 w:1)
	/// Proof: `ProjectTips::Projects` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_project() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `10`
		//  Estimated: `3475`
		// Minimum execution time: 13_363_000 picoseconds.
		Weight::from_parts(14_074_000, 3475)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
}
