
//! Autogenerated weights for `pallet_department_funding`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-10-09, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `amiya`, CPU: `12th Gen Intel(R) Core(TM) i7-12650H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// target/release/node-template
// benchmark
// pallet
// --chain
// dev
// --wasm-execution
// compiled
// --pallet
// pallet-department-funding
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// custom-pallets/department-funding/src/weights.rs
// --template=./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_department_funding`.
pub trait WeightInfo {
	fn create_department_required_fund() -> Weight;
}

/// Weights for `pallet_department_funding` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Departments::Departments` (r:1 w:0)
	/// Proof: `Departments::Departments` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `DepartmentFunding::NextDepartmentRequiredFundId` (r:1 w:1)
	/// Proof: `DepartmentFunding::NextDepartmentRequiredFundId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `DepartmentFunding::DepartmentRequiredFunds` (r:0 w:1)
	/// Proof: `DepartmentFunding::DepartmentRequiredFunds` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_department_required_fund() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `345`
		//  Estimated: `3810`
		// Minimum execution time: 26_415_000 picoseconds.
		Weight::from_parts(27_367_000, 3810)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Departments::Departments` (r:1 w:0)
	/// Proof: `Departments::Departments` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `DepartmentFunding::NextDepartmentRequiredFundId` (r:1 w:1)
	/// Proof: `DepartmentFunding::NextDepartmentRequiredFundId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `DepartmentFunding::DepartmentRequiredFunds` (r:0 w:1)
	/// Proof: `DepartmentFunding::DepartmentRequiredFunds` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_department_required_fund() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `345`
		//  Estimated: `3810`
		// Minimum execution time: 26_415_000 picoseconds.
		Weight::from_parts(27_367_000, 3810)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
}
